import BackgroundAnimation from "@/libs/components/BackgroundAnimation/BackgroundAnimation";
import Footer from "@/libs/components/Footer/Footer";
import Header from "@/libs/components/Header/Header";
import { theme } from "@/libs/theme";
import { ChakraBaseProvider } from "@chakra-ui/react";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ChakraBaseProvider theme={theme}>
          <BackgroundAnimation />
          <Header />
          {children}
          <Footer />
        </ChakraBaseProvider>
      </body>
    </html>
  );
}
