import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/libs/components/Header/Header";
import Footer from "@/libs/components/Footer/Footer";
import { ChakraBaseProvider } from "@chakra-ui/react";
import { theme } from "@/libs/theme";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ChakraBaseProvider theme={theme}>
          <Header />
          {children}
          <Footer />
        </ChakraBaseProvider>
      </body>
    </html>
  );
}
